---

- name: Check OS version and family
  tags:
    - always
  ansible.builtin.assert:
    that: (ansible_distribution != 'CentOS' and ansible_os_family == 'RedHat' or ansible_os_family == "Rocky") and ansible_distribution_major_version is version_compare('9',
      '==')
    fail_msg: This role can only be run against RHEL/Rocky 9 families. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported.
    success_msg: This role is running against a supported OS {{ ansible_distribution }} {{ ansible_distribution_major_version }}
  when:
    - not skip_os_check

- name: Check ansible version
  tags:
    - always
  ansible.builtin.assert:
    that: ansible_version.full is version_compare(min_ansible_version, '>=')
    fail_msg: You must use Ansible {{ min_ansible_version }} or greater
    success_msg: This role is running a supported version of ansible {{ ansible_version.full }} >= {{ min_ansible_version }}

- name: Setup rules if container
  tags:
    - container_discovery
    - always
  when:
    - ansible_connection == 'docker' or ansible_virtualization_type in ["docker", "lxc", "openvz", "podman", "container"]
  block:
    - name: Discover and set container variable if required
      ansible.builtin.set_fact:
        system_is_container: true

    - name: Load variable for container
      ansible.builtin.include_vars:
        file: "{{ container_vars_file }}"

    - name: output if discovered is a container
      when:
        - system_is_container
      ansible.builtin.debug:
        msg: system has been discovered as a container

- name: Check password set for connecting user
  when:
    - ansible_env.SUDO_USER is defined
    - not system_is_ec2
  block:
    - name: Capture current password state of connecting user"
      ansible.builtin.shell: "grep {{ ansible_env.SUDO_USER }} /etc/shadow | awk -F: '{print $2}'"
      changed_when: false
      failed_when: false
      check_mode: false
      register: ansible_user_password_set

    - name: Assert that password set for {{ ansible_env.SUDO_USER }} and account not locked
      tags:
        - user_passwd
      ansible.builtin.assert:
        that: ansible_user_password_set.stdout | length != 0 and ansible_user_password_set.stdout != "!!"
        fail_msg: You have {{ sudo_password_rule }} enabled but the user = {{ ansible_env.SUDO_USER }} has no password set - It can break access
        success_msg: You have a password set for the {{ ansible_env.SUDO_USER }}
      vars:
        sudo_password_rule: RHEL-09-010380  # pragma: allowlist secret

- name: Include OS specific variables
  tags:
    - always
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Check rhel9stig_bootloader_password_hash variable has been changed
  tags:
    - grub
  when:
    - not system_is_ec2
    - not system_is_container
    - rhel_09_212010
    - rhel9stig_set_bootloader_password
  ansible.builtin.assert:
    that: rhel9stig_bootloader_password_hash != 'grub.pbkdf2.sha512.changethispassword'  # pragma: allowlist secret
    msg: This role will not be able to run single user password commands as rhel9stig_bootloader_password_hash variable has not been set  # pragma: allowlist secret

- name: Gather the package facts
  tags:
    - always
  ansible.builtin.package_facts:
    manager: auto

- name: Include prelim tasks
  tags:
    - prelim_tasks
    - run_audit
  ansible.builtin.import_tasks: prelim.yml

- name: Include pre-remediation tasks
  tags:
    - run_audit
  when:
    - run_audit
    - setup_audit
  ansible.builtin.import_tasks: pre_remediation_audit.yml

- name: Include CAT I patches
  tags:
    - CAT1
    - high
  when: rhel9stig_cat1
  ansible.builtin.import_tasks: Cat1/main.yml

- name: Include CAT II patches
  ansible.builtin.import_tasks: Cat2/main.yml
  when: rhel9stig_cat2
  tags:
    - CAT2
    - medium

# - name: Include CAT III patches
#   ansible.builtin.import_tasks: Cat3/main.yml
#   when: rhel9stig_cat3
#   tags:
#       - CAT3
#       - low

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reboot system
  when:
    - change_requires_reboot
    - not rhel9stig_skip_reboot
  block:
    - name: reboot system if not skipped
      ansible.builtin.reboot:

    - name: Warning a reboot required but skip option set
      when:
        - change_requires_reboot
        - rhel9stig_skip_reboot
      ansible.builtin.debug:
        msg: Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results
      changed_when: true

- name: run post remediation audit
  tags:
    - run_audit
  when:
    - run_audit
  ansible.builtin.import_tasks: post_remediation_audit.yml

- name: Show Audit Summary
  tags:
    - run_audit
  when:
    - run_audit
  ansible.builtin.debug:
    msg: "{{ audit_results.split('\n') }}"

- name: If Warnings found Output count and control IDs affected
  tags:
    - always
  when: warn_count != 0
  ansible.builtin.debug:
    msg: You have {{ warn_count }} Warning(s) that require investigating that are related to the following benchmark ID(s) {{ warn_control_list }}
